[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
vault_policy = "VFP1111111111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/vaultforge-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
