apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vaultforge.fullname" . }}-secrets
  labels:
    {{- include "vaultforge.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.secrets.DATABASE_URL | b64enc | quote }}
  JWT_SECRET: {{ .Values.secrets.JWT_SECRET | b64enc | quote }}
  WEBHOOK_SECRET: {{ .Values.secrets.WEBHOOK_SECRET | b64enc | quote }}
